### ISSUE TITLE
 mm2-fast is not giving the same results as minimap2

### ISSUE THREAD

**Issue by Rafaelsoler13** [bwa-mem2/mm2-fast#8]
Hello,

I have being trying with mm2-fast, but checking if the output between the two tools are the same, I realize that they are not.

I did:

mm2-fast folder
./minimap2 -c --eqx samples/chimp.fasta samples/human.fasta --max-chain-skip=1000000 > new_minimap2.paf

minimap2 folder
./minimap2 -c --eqx samples/chimp.fasta samples/human.fasta --max-chain-skip=1000000 > old_minimap2.pa

And the results are a few lines different.
```
8d7
< hg38_dna	8029450	7562342	7571092	-	panTro6_dna	8059761	5494248	5503002	8515	8798	0	NM:i:283	ms:i:16058	AS:i:15974	nn:i:0	tp:A:S	cm:i:1070	s1:i:6886	de:f:0.0250	rl:i:376244	cg:Z:39=1I22=11D16=1X94=1X7=1X23=1X4=2X6=1X32=2D9=4X1=3D9=1X175=1X72=1X21=1X52=1X63=1X9=1X7=1X42=1X42=1X83=1X65=1I8=1X60=1X37=1X28=1X1=1X27=6D3=2D113=1X22=1X24=1X29=1X20=1X13=1X47=1X16=1X33=1X35=1X65=1X3=1X24=1X171=1D115=1X3=1X34=2X6=1X6=1I48=1X13=1X7=1X50=1X63=1X10=4I8=1X126=1X24=2X20=1X6=1X16=1X6=1X50=1X37=1X15=1X66=1X30=1X24=2D12=1X80=1I37=1X68=1X44=1X25=1X94=1X28=1X16=1X8=1D9=1X31=2X91=1X76=1X66=1X1=1X14=1X5=1X56=1X159=1X8=1X17=1X23=1X7=1X6=1X10=1D30=1X29=1X2=1I1X27=2X46=1X21=7D35=1X4=1X49=2I13=1X15=1X108=1X9=1X44=1X8=1X21=1X126=1X25=1X7=1X40=1X5=2X16=2X17=1X176=1X53=1X234=1X36=1X16=11I2=1X6=1X15=1X19=1X13=6D47=1X126=1X102=2X3=1X87=1X2=10I60=2I40=1X108=4I112=1X186=1X2=1X64=1D13=1X6=1X16=1X9=1X92=1X40=1X14=4I15=1X20=1X147=1X20=1X8=1X75=1X25=1X60=1D55=1X1=1X92=1X1=1X89=1X133=1X25=1X89=4D20=1X26=1X65=2X125=1X35=1X174=1X10=1X11=1X123=2I41=1X73=1X21=1X55=1X64=2X12=1X9=2X170=1X39=1X1=1X2=2X19=1X44=1X137=1X95=1X22=1X8=1X8=1X25=1X16=1X10=1X47=1X86=1X71=1X11=1X10=1X9=3X4=1X120=
38a38
> hg38_dna	8029450	6807903	6810340	+	panTro6_dna	8059761	2719712	2722162	1841	2608	0	NM:i:767	ms:i:1279	AS:i:957	nn:i:0	tp:A:S	cm:i:14	s1:i:140	de:f:0.2212	rl:i:376244	cg:Z:6=1X2=1X3=1I7=1X22=1X2=1I2=1X1=1X2=11D2=1X7=1X2=2X4=1X2=1X1=1X3=1X2=1X3=1X1=1I4=1X1=1D1X7=1X2=3I7=1D8=3X2=1I2=1I1=2X3=9I23=1X7=1X1=1X1=1X3=2X3=1X5=1X10=2X3=2X3=1X1=4D3=1X2=1I7=1X6=2X2=5I3=1X8=1X1=3I1=1D2=1X4=1X3=2I1X7=1X6=2D3=2I2=1X1=1X3=1X12=2X1=1X18=10I2=8I8=1X1=3X14=1I15=1X6=1X5=1X3=1X2=13I1=1X1=1I13=1X5=1X8=1X23=1X2=1X2=2X9=1X5=1X4=2X3=1X2=1X2=1X5=2X6=1X9=1X4=1X3=2D2=1X8=3X5=3I1X2=3D4=1X9=1X3=3D2=3X10=1X2=1X4=1X1=1X1=2X6=2X4=2D2=1I6=1X5=1X1=1X2=1X1=1X1=1I1X1=1X2=1X1=1X4=1X3=1X8=1X5=2X1=1X2=1X5=2X1=1D2=1X17=2X1=1X1=1X3=1X2=1X7=1X1=2X3=1X1=1X14=2X2=2X1=1X5=2X4=1X3=1X3=1X20=1D1=1X8=1X11=3I3=3X11=2X5=2X2=1X5=1X4=1X2=1X4=1X2=1X1=1X2=1X4=1X7=1X4=3D1X1=1D11=3X4=1X1=1X6=1X5=2X6=2X3=1X2=1X1=2X3=1X3=1X4=1X4=1X7=5X13=1I4=1X3=1X2=13I2=1X6=3I2=4I4=1I3=1I3=1X13=1X7=1I5=1D3=1X5=2X8=1I2=1X1=1X3=1X1=1X1=1X2=2X12=2X3=2X1=1X24=1X4=1X2=1X2=1X10=1X4=1X4=1X4=1X4=2X2=1X4=3X2=1X1=1X5=1X4=2I1=1X3=1X4=2X3=3X3=1X1=3D5=1X7=1X4=1X4=1X4=2X1=2X20=1X8=2X7=1X2=1X6=1X3=2X3=1X3=4D3=3D2=1X3=1D1X4=5D2=7D3=1D4=1I3=1D2X1=2X9=1X1=1X5=2X11=3X9=1X5=1X2=1X6=1X3=1X2=1X2=22I4=1X2=1X2=2X5=1X2=1X7=1X2=1X4=1I2=1X1=1D2=1X2=2X4=1X5=1X6=1X3=1D2X1=1X2=1X18=1X2=1X6=1X8=6D2=1D4=2D2=1X4=1X1=1X4=1X7=2X2=1X6=1X4=1X9=2X2=1X7=2X3=1X3=1X2=1X2=1X3=1X6=1X2=1X8=1X3=1X2=1X7=1D4=1I8=1X7=1X2=1X1=3X6=1X3=2X2=1X2=1X5=1X1=1X1=2X8=1X3=2I1=4I1=1I3=7I3=1X4=2X2=1X2=2X2=1X1=1X5=1X3=2X1=2D1=1X7=1X5=2X1=3I2X5=1X7=1X5=1X3=1X1=5X1=2X1=2X2=1X3=2X5=2X1=1X5=1X7=1X4=39D17=2X2=2D2=1D3=3D6=1X5=1X6=1X1=1X1=1X16=2X7=1X6=1X2=1X4=1X2=1X7=1X5=2X2=1X8=1X7=2X2=1X7=1X2=2X4=1X3=1X3=2X12=1X1=3X18=5I7=4I2=1I2=1X6=4I3=1X8=1X1=1X5=1X3=1X1=2X1=1X4=1X2=2X5=1X7=1X2=1X9=1X1=2D1=1X5=1X2=1X6=1D1=1X2=1X1=2D4=4I1X18=1X2=24D4=1X1=1D3=1X1=1X2=1X6=11D5=9D10=3X7=1X7=1X10=1X14=2X12=1X1=2X2=1X9=2X5=1X13=
100c100
< hg38_dna	8029450	7573597	7573979	-	panTro6_dna	8059761	5492656	5493063	336	409	58	NM:i:73	ms:i:468	AS:i:430	nn:i:0	tp:A:P	cm:i:11	s1:i:94	s2:i:59	de:f:0.1227	rl:i:376244	cg:Z:15=1X7=1X14=1X14=1X6=1X1=1X8=1X1=1X1=2I5=1X2=1X3=1X4=1X2=1X18=1X4=2X7=1X7=1X3=1X6=2X19=1X13=1X10=1X2=1X8=1X29=3X7=1X3=1X1=1X1=1X5=1X6=3D1=1X9=1X5=1X1=1X1=1X10=1X1=1X10=1X43=24D3=1X17=1X3=
---
> hg38_dna	8029450	7573597	7573979	-	panTro6_dna	8059761	5492656	5493063	336	409	60	NM:i:73	ms:i:468	AS:i:430	nn:i:0	tp:A:P	cm:i:11	s1:i:94	s2:i:0	de:f:0.1227	rl:i:376244	cg:Z:15=1X7=1X14=1X14=1X6=1X1=1X8=1X1=1X1=2I5=1X2=1X3=1X4=1X2=1X18=1X4=2X7=1X7=1X3=1X6=2X19=1X13=1X10=1X2=1X8=1X29=3X7=1X3=1X1=1X1=1X5=1X6=3D1=1X9=1X5=1X1=1X1=1X10=1X1=1X10=1X43=24D3=1X17=1X3=
486d485`
```

Best,

Rafael

**Comment by SaurabhKalikar** [comment]
Hello @Rafaelsoler13 

Could you please point me to the datasets: samples/chimp.fasta  and samples/human.fasta? I will try at my and and get back to you soon.

Thanks,
Saurabh

**Comment by Rafaelsoler13** [comment]
Thanks for the quick response! :)

[chimp.txt](https://github.com/bwa-mem2/mm2-fast/files/11294060/chimp.txt)
[human.txt](https://github.com/bwa-mem2/mm2-fast/files/11294061/human.txt)

**Comment by SaurabhKalikar** [comment]
Hello @Rafaelsoler13 

Sorry for the late response. 

I tried your datasets at my end and turns out that the output for both minimap2 and mm2-fast matches.

**_Log for minimap2_**
``
[M::mm_idx_gen::0.214*1.00] collected minimizers
[M::mm_idx_gen::0.284*1.47] sorted minimizers
[M::main::0.284*1.47] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.301*1.45] mid_occ = 67
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.315*1.43] distinct minimizers: 1234413 (94.16% are singletons); average occurrences: 1.173; average spacing: 5.568; total length: 8059761
[M::worker_pipeline::16.640*1.01] mapped 1 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: ./minimap2-2.24/minimap2 -c --eqx --max-chain-skip=1000000 ./datasets/chimp.fasta ./datasets/human.fasta
[M::main] Real time: 16.685 sec; CPU: 16.780 sec; Peak RSS: 0.315 GB
``

**_Log for mm2-fast_**
``
[M::mm_idx_gen::0.237*1.01] collected minimizers
[M::mm_idx_gen::0.313*1.48] sorted minimizers
[M::main::0.313*1.48] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.330*1.45] mid_occ = 67
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.343*1.44] distinct minimizers: 1234413 (94.16% are singletons); average occurrences: 1.173; average spacing: 5.568; total length: 8059761
minimizer-lookup: 0 dp: 0 rmq: 0 rmq_t1: 0 rmq_t2: 0 rmq_t3: 0 rmq_t4: 0 alignment: 0
[M::worker_pipeline::5.755*1.08] mapped 1 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: ./mm2-fast/minimap2 -c --eqx --max-chain-skip=1000000 ./datasets/chimp.fasta ./datasets/human.fasta
[M::main] Real time: 5.802 sec; CPU: 6.280 sec; Peak RSS: 0.365 GB
``

**Output PAF file size: 639K**
[minimap2_paf.txt](https://github.com/bwa-mem2/mm2-fast/files/11589213/minimap2_paf.txt)
[mm2-fast_paf.txt](https://github.com/bwa-mem2/mm2-fast/files/11589214/mm2-fast_paf.txt)

Could you please confirm whether you get the same PAF output? 

Thanks,
Saurabh

**Comment by sanchit-misra** [comment]
I am closing this issue since @SaurabhKalikar has already verified that the output matches and there is no response from @Rafaelsoler13.

@Rafaelsoler13 : please note that the mm2-fast is compatible with minimap2 v2.24.
